name: mdc_web_components
description: (Pseudo) Web components for the mdc_web package.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jacob Phillips <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
 mdc_web: ^0.4.0
 meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0
